development:
  clients:
    default:
      database: test
      hosts:
        - 164.132.49.9:27017
      options:
        

  options:
  

test:
  clients:
    default:
      database: test
      hosts:
        - 164.132.49.9:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: test
      hosts:
- 164.132.49.9:27017
